import {test,expect} from '@playwright/test';
import fs from 'node:fs';
import {zipSync,strToU8,unzipSync} from 'fflate';
test('demo recovers content, downloads valid archive, and stays local',async({page})=>{
 const unexpected=[];page.on('request',r=>{if(!r.url().startsWith('http://127.0.0.1:4178')&&!r.url().startsWith('data:'))unexpected.push(r.url());if(r.method()!=='GET')unexpected.push(r.method());});
 await page.setViewportSize({width:1280,height:1100});await page.goto('/');await page.screenshot({path:'docs/before.png',fullPage:false});await page.getByRole('button',{name:'Just looking?'}).click();await expect(page.locator('#result')).toBeVisible();await expect(page.locator('#counts')).toHaveText('8 paragraphs · 1 embedded image');
 const preview=page.frameLocator('#preview');await expect(preview.locator('img')).toBeVisible();expect(await preview.locator('img').evaluate(i=>i.complete&&i.naturalWidth>0)).toBe(true);await expect(preview.locator('p').first()).toHaveText('The little garden journal');await page.screenshot({path:'docs/after.png',fullPage:false});
 const downloadPromise=page.waitForEvent('download');await page.locator('#zip').click();const download=await downloadPromise;const archive=unzipSync(fs.readFileSync(await download.path()));expect(Object.keys(archive)).toContain('images/garden.png');expect(new TextDecoder().decode(archive['recovered.txt'])).toContain('Some things are worth keeping.');expect(unexpected).toEqual([]);
 await page.getByRole('button',{name:'Open another file'}).click();await expect(page.locator('#result')).toBeHidden();
});
test('rejects binary, malformed XML, entities and archive expansion',async({page})=>{
 await page.goto('/');for(const buffer of [Buffer.from('old binary file'),Buffer.from(zipSync({'summary.xml':strToU8('<bad'),'story/1.xml':strToU8('<x/>')})),Buffer.from(zipSync({'summary.xml':strToU8('<!DOCTYPE x><x/>'),'story/1.xml':strToU8('<x/>')})),Buffer.from(zipSync({'oversized':new Uint8Array(100000001)}))]){await page.locator('#file').setInputFiles({name:'test.ppp',mimeType:'application/octet-stream',buffer});await expect(page.locator('#status')).toHaveClass('error');await expect(page.locator('#result')).toBeHidden();}
});
test('escapes injected document HTML',async({page})=>{await page.goto('/');const buffer=Buffer.from(zipSync({'summary.xml':strToU8('<SerifXML><Summary Title="&lt;script&gt;"/></SerifXML>'),'story/1.xml':strToU8('<x><p>&lt;img src=x onerror=alert(1)&gt;</p></x>')}));await page.locator('#file').setInputFiles({name:'injection.ppp',mimeType:'application/octet-stream',buffer});await expect(page.frameLocator('#preview').locator('p')).toHaveText('<img src=x onerror=alert(1)>');await expect(page.frameLocator('#preview').locator('script,img')).toHaveCount(0);});
test('responsive at common widths',async({page})=>{for(const width of [375,768,1024,1440]){await page.setViewportSize({width,height:900});await page.goto('/');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}await page.setViewportSize({width:375,height:812});await page.screenshot({path:'docs/mobile.png',fullPage:true});});
if(process.env.PPP_SAMPLE_DIR)for(const [name,count,images]of [['customising',104,19],['graph-paper',38,4]])test('real sample '+name,async({page})=>{await page.goto('/');await page.locator('#file').setInputFiles(`${process.env.PPP_SAMPLE_DIR}/${name}.ppp`);await expect(page.locator('#result')).toBeVisible();const paragraphs=await page.frameLocator('#preview').locator('p').allTextContents();expect(paragraphs.length).toBe(count);if(process.env.PPP_EXPECTED_DIR){const expected=JSON.parse(fs.readFileSync(`${process.env.PPP_EXPECTED_DIR}/${name}/recovered.json`)).stories.flatMap(s=>s.paragraphs);expect(paragraphs).toEqual(expected);}await expect(page.frameLocator('#preview').locator('img')).toHaveCount(images);expect(await page.frameLocator('#preview').locator('img').evaluateAll(imgs=>imgs.every(i=>i.complete&&i.naturalWidth>0))).toBe(true);});

test('recovers bin images, lists every image, and reports missing resources and fields',async({page})=>{
 await page.goto('/');const image=fs.readFileSync('public/demo-art.png');
 const input=zipSync({'summary.xml':strToU8('<SerifXML><Summary Title="Image recovery"/></SerifXML>'),'story/1.xml':strToU8('<x><p>Hello</p><p><glyph _class="GlyphFieldPageNumber" _id="field1"/></p></x>'),'resources.xml':strToU8('<x><r _id="img1" _class="BitmapResource" Data="_bin_bin\\photo.bin"/><r _id="img2" _class="BitmapResource" Data="_bin_images\\absent.png"/><r _id="img3" _class="BitmapResource" Data="_bin_images\\raw.wdp"/></x>'),'bin/photo.bin':image,'images/raw.wdp':strToU8('unsupported')});
 await page.locator('#file').setInputFiles({name:'images.ppp',mimeType:'application/octet-stream',buffer:Buffer.from(input)});await expect(page.locator('#result')).toBeVisible();await expect(page.locator('#counts')).toHaveText('2 paragraphs · 1 embedded image');await expect(page.locator('#warnings')).toContainText('1 image resource(s)');await expect(page.locator('#warnings')).toContainText('1 embedded image resource(s)');await expect(page.locator('#warnings')).toContainText('1 automatic field');
 await page.locator('#gallery summary').click();await expect(page.locator('#gallery-items img')).toHaveCount(1);await expect.poll(()=>page.locator('#gallery-items img').evaluate(i=>i.complete&&i.naturalWidth>0)).toBe(true);
 const next=page.waitForEvent('download');await page.locator('#zip').click();const zip=unzipSync(fs.readFileSync(await (await next).path()));const imgName=Object.keys(zip).find(n=>n.endsWith('.png'));expect(Buffer.from(zip[imgName])).toEqual(image);expect(new TextDecoder().decode(zip['recovered.html'])).toContain(imgName);
 const single=page.waitForEvent('download');await page.locator('#gallery-items a').click();expect(fs.readFileSync(await(await single).path())).toEqual(image);
 await page.getByRole('button',{name:'Open another file'}).click();await expect(page.locator('#gallery-items a')).toHaveCount(0);
});
