import {recover,htmlDocument,imageType} from './parser.js';
import {zipSync,strToU8} from 'fflate';
const $=id=>document.getElementById(id);let current=null;let imageUrls=[];
function clearImages(){for(const url of imageUrls)URL.revokeObjectURL(url);imageUrls=[];$('gallery-items').replaceChildren();$('gallery').hidden=true;$('gallery').open=false;}
function showImages(){clearImages();const entries=Object.entries(current.assets);$('gallery').hidden=!entries.length;$('gallery-title').textContent=`All recovered images (${entries.length})`;
 for(const [name,bytes] of entries){const url=URL.createObjectURL(new Blob([bytes],{type:`image/${imageType(bytes)==='jpg'?'jpeg':imageType(bytes)}`}));imageUrls.push(url);const link=document.createElement('a');link.href=url;link.download=name.slice(7);const img=document.createElement('img');img.src=url;img.alt='Recovered image: '+name.slice(7);img.loading='lazy';const caption=document.createElement('span');caption.textContent=name.slice(7)+' ↓';link.append(img,caption);$('gallery-items').append(link);img.onerror=()=>{img.alt='Image could not be decoded';caption.textContent=name.slice(7)+' — preview unavailable; download original';};}
}

function save(bytes,name,type){const url=URL.createObjectURL(new Blob([bytes],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
async function open(file){if(!file)return;clearImages();current=null;$('result').hidden=true;$('status').className='';$('status').textContent='Opening your document locally…';$('demo').disabled=true;$('file').disabled=true;document.querySelector('label.primary').classList.add('disabled');try{if(file.size>30e6)throw Error('Please choose a file smaller than 30 MB.');await new Promise(r=>setTimeout(r,30));current=recover(await file.arrayBuffer());$('result-title').textContent=current.title;$('counts').textContent=`${current.paragraphs.length} paragraphs · ${Object.keys(current.assets).length} embedded image${Object.keys(current.assets).length===1?'':'s'}`;$('warnings').replaceChildren(...current.warnings.map(w=>{const li=document.createElement('li');li.textContent=w;return li;}));$('preview').srcdoc=htmlDocument(current,true);showImages();$('result').hidden=false;$('status').textContent='Recovered locally. Review your document below.';$('result').scrollIntoView({behavior:'instant',block:'start'});}catch(e){$('status').textContent=e.message||'This file could not be opened.';$('status').className='error';}finally{$('demo').disabled=false;$('file').disabled=false;document.querySelector('label.primary').classList.remove('disabled');}}
$('file').addEventListener('change',e=>open(e.target.files[0]));
for(const name of ['dragover','drop'])$('drop').addEventListener(name,e=>{e.preventDefault();if(name==='drop'){$('drop').classList.remove('drag');if(!$('file').disabled)open(e.dataTransfer.files[0]);}else $('drop').classList.add('drag');});$('drop').addEventListener('dragleave',()=>$('drop').classList.remove('drag'));
$('demo').onclick=async()=>{try{const r=await fetch('/demo.ppp');if(!r.ok)throw Error('Demo unavailable. Please try again.');await open(new File([await r.blob()],'demo.ppp'));}catch(e){$('status').textContent=e.message;}};
$('reset').onclick=()=>{clearImages();current=null;$('result').hidden=true;$('preview').srcdoc='';$('file').value='';$('status').textContent='';$('file').focus();window.scrollTo({top:0});};
$('html').onclick=()=>current&&save(htmlDocument(current,true),'recovered.html','text/html');
$('txt').onclick=()=>current&&save(current.paragraphs.join('\n\n'),'recovered.txt','text/plain');
$('zip').onclick=()=>{if(!current)return;save(zipSync({...current.assets,'recovered.html':strToU8(htmlDocument(current)),'recovered.txt':strToU8(current.paragraphs.join('\n\n')),'READ-ME.txt':strToU8('Recovered with PPP Rescue. Reflowed text and embedded images only. Original layout, vectors, fonts and some inline objects are not preserved.\n'+current.warnings.join('\n'))}),'recovered.zip','application/zip');};
